FROM node:24.11-bookworm-slim
ENV NODE_ENV=development
ARG TESTING=false
ENV TESTING=$TESTING

WORKDIR /src
COPY --link package.json package-lock.json ./
RUN if [ "$TESTING" = "true" ]; then npx playwright install --with-deps; fi
RUN npm i
CMD [ "npm", "run", "dev" ]
